### ISSUE TITLE
big_trace.trace isn't parsed correctly

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#10]
In my last push, all I did was move our TraceOptions type out of trace.h and into defs.h so our Cache didn't need to accept all of the object (and added cache.h to main). I do not think that broke anything, but when I tested it, big_trace.trace wasn't working. Can someone give me feedback on that?

**Comment by krustchinsky** [comment]
The big trace is broken because when he generated it, he accidentally left a few thousand lines of nothing but tabs following the actual data. There is a new version of the big trace on Blackboard.
