### ISSUE TITLE
this->

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#13]
I don't understand our explicit use of the "this" pointer. We only need it in cases were our parameters share names with our class members, right?

**Comment by krustchinsky** [comment]
No. This is basically returns a reference to the object you are currently it. It is a very hard concept to explain simply, I'd recommend reading on it a little bit.

http://www.learncpp.com/cpp-tutorial/87-the-hidden-this-pointer/

I use "this" whenever I am access data members or functions inside of an objects implementation (.cpp), it helps simply differentiate what belongs to a class and what doesn't. It's not required, just syntactic sugar to help read things more easily.

**Comment by T-King** [comment]
I will take time and read more about this->
