### ISSUE TITLE
type MemoryAddress

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#14]
I've been trying to wrap my head around assigning values to our blockAddress bitset<> in our cache class, but I think one problem is our MemoryAddress type in our trace class. It might be better if we read the addresses in as strings, based on Mashiro's bit manipulation example. That way we can go straight to binary with bitset and use a temporary value to operate on 
(i.e. temp % this->blocks == this->lines.blockAddress)

**Comment by T-King** [comment]
That example is not quite true because we would need to set it to binary with bitset, but that's not really the point.

**Comment by krustchinsky** [comment]
I'm currently working on this too, I'm toying around with bitset bit manipulation, if I can't figure it out by the end of the night I'll just change the type of the MemoryAddress in defs.h to a std::string and we can write a few conversion functions.

**Comment by T-King** [comment]
I'll take it as a small personal victory that I at least understand the problem and leave it to you for now. And I'll check back in later tonight and tomorrow to see what's up. Maybe comment again on this issue if you've come up with something you're satisfied with.

**Comment by krustchinsky** [comment]
Ok sounds good!

**Comment by krustchinsky** [comment]
I've added some stuff, and I expect by the end of tonight to be able to extract of all of the necessary data for a cache line from a memory address. From there we just need to simulate the read/writes and count misses and hits.

**Comment by T-King** [comment]
wow great. I'm trying to read through everything right now, but you did quite a lot so it'll take me a few.

**Comment by T-King** [comment]
So at one point I used an empty copy constructors in Trace to get around copying our trace object into our cache object because of our use of "delete". How did you work around it?

**Comment by T-King** [comment]
so now for our simulate() it loops for the size of our 'lines' vector and creates lines with a new method, and in the debug mode prints the information, correct?
