### ISSUE TITLE
Add a valid bit

### ISSUE THREAD

**Issue by krustchinsky** [CSCE360025/Project#16]
When I get home from work, I'm going to add a std::bitset<1> to the CacheLine struct which will be our valid bit. This is a requirements for the project.

**Comment by ScotuFlash** [comment]
What is the valid bit going to do? I'm looking at our cache struct currently, I can probably add this in if you want.

**Comment by T-King** [comment]
It's already fixed.

**Comment by ScotuFlash** [comment]
Yeah, now I see that you changed it. Didn't go through until 4 minutes ago. Anything I can help with at the moment?

**Comment by T-King** [comment]
Yea we still need to determine how to identify a cache miss and what to do with it.

**Comment by T-King** [comment]
We can populate the cache atm and that's about it.

**Comment by ScotuFlash** [comment]
Please correct me in any way so I can catch up, but now that we have the cache populated we have the "tag" and "block address". What exactly are we supposed to be comparing these to? Are we just reading back in the trace and comparing the addresses to those we stored in our cache lines?
