### ISSUE TITLE
Code cleaning and verification

### ISSUE THREAD

**Issue by krustchinsky** [CSCE360025/Project#18]
I think things are working. I think. Let's test, clean, and document. Hits and misses seem to be working.

**Comment by T-King** [comment]
Give me some time to look at it. I took a nap and was making food, expecting to work on it after that. I woke up and it was done. lol.

**Comment by T-King** [comment]
Why did you  comment out the code for resize()? I know it's not really a useful function, but the number that we get from the user is like 64 or 128. Besides being an incredibly tiny cache, even if we interpreted it as 64000, that's still not a power of 2. The whole point of that function was to give us the exact number of cache lines so we would only need to adjust the size of our container once.

**Comment by T-King** [comment]
Also, aren't we only assigning 1 memory address per cacheline with this implementation? If I read it right, this still won't populate a single cacheline with 4 address. But that is the part I'm still having trouble wrapping my head around and I'm watching tutorials still.

**Comment by krustchinsky** [comment]
The resize function is going to be removed in favor of just dynamically allocating an array of CacheLines. The number of cache lines is sizeL1/32, so in the case of a 32k sizel1, 1024 cache lines should be expected.

Vectors aren't fixed sized containers. Read on the resize() function for std::vector<>, it doesn't do what you think it does. 

I'm currently working on the multiple cache lines in a single index, I'm reading on why that happens and how to implement that use case.

**Comment by T-King** [comment]
I think what we need to do is handle the offset like we currently are (just setting it), then using 
(line - offset) % number_of_cachelines. The block address should be the same for the entire block (4 address from main memory at a time), and the tag is comprised of the remaining nibble from each address. Although that would only account for 31 bits. Not sure about the 17th bit in the tag.

**Comment by T-King** [comment]
Also, Jake: Sweany said the "re" entrance exam is next Friday. I forgot to say anything and I cant remember if you were there to hear that.

**Comment by krustchinsky** [comment]
Yeah, a friend told me. Thanks for the heads up though

**Comment by T-King** [comment]
![1429249399774-306153159](https://cloud.githubusercontent.com/assets/11350437/7196611/ccb7c9d8-e49a-11e4-81cc-3cdc0f601f40.jpg)

**Comment by T-King** [comment]
Is that how it works?
