### ISSUE TITLE
Are we ready?

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#19]
The numbers look good now. I just ran it with the 3 trace files and the numbers are reasonable. Do we all think it's ready now?

**Comment by krustchinsky** [comment]
When I get home from work around 1500 or 1600 I will take some time to clean some of the code up, document things, and add some more debug functionality. I expect to have things finalized by 1800 or 1900 tonight and then we should be good to turn things in. The numbers do look reasonable and from here let's just clean, document, and continue testing. 

There were a few things valgrind yelled about (possible memory leaks) that I'm going to look into. I'm going to push up a change in a few hours and tag it as V2.0. Consider that a "turn-in ready version".

**Comment by T-King** [comment]
What all do you feel like we need to clean up? I might be able to address some of it, although I don't have access to valgrind. As far as bug testing goes, we really don't have much variation outside of the command-line arguments. We just to make sure the numbers stay good for varying cache sizes.

**Comment by T-King** [comment]
I want to also take this time to say I got an email from the grader saying he had no submissions for assignment 2. I remember that assignment not going very well for our group, but if we had some submission, we can turn it in, or we can throw something together submit it now.

**Comment by krustchinsky** [comment]
It was turned in via-email to him from me because Blackboard was down the night it was due. I've sent him e-mails about this before, he may just keep forgetting. I'll shoot him an E-mail to let him know again.
