### ISSUE TITLE
Implementing feedback

### ISSUE THREAD

**Issue by krustchinsky** [CSCE360025/Project#21]
This weekend I will work into the code some recommendations made to me from the TA. He has a few concerns about specific things in our simulation, but besides that everything looks fine.

I'm going to take some time this weekend to review your code Troy and start building a list of what needs to be finished/polished. Everything looks good thus far!

**Comment by T-King** [comment]
I created a new branch called dev2. After some thinking, I realized I could make my implementation much more compact and robust. Please reference it first!!

It does not work for some reason that I can't figure out. Something about an undefined reference to what was originally the createCacheLine() method. But I still think it's closer to what we want.

**Comment by T-King** [comment]
Please reply soon because it does change a lot.

**Comment by krustchinsky** [comment]
I'm working on figuring out how we can effectively simulate both direct and full with your implementation. I might need to re-work things.

We need to look at both the L1 and L2 caches not as separate object but as members of the overall Cache object. That way we can more easily simulate either type of cache (full/direct) without passing around refs. Come to a stopping point with your implementation and I'll start working on re-organizing things.

The todo list so far is to just re-work some structure, implement full associativity (not hard I think) and then to just add the L2 logic in the simulate methods leveraging your existing code which describes and construct the L2 cache.

**Comment by T-King** [comment]
Jake, check this out now. It's gooder.

**Comment by T-King** [comment]
*bump*

**Comment by krustchinsky** [comment]
Checking it out now

**Comment by krustchinsky** [comment]
Looks great, exactly what I was thinking. I'll start working away on getting the full simulation working and implementing the L2 logic

**Comment by krustchinsky** [comment]
So to account for the addition of the L2 cache, I think I'll rework it so that there is just another set of CacheLine members. I'll add additionally hit and miss functions as well. So L1 and L2 cache will have their own set of hit/miss functions, and CacheLine structs.
```c++
		DirectCacheLine* L1DirectLines;
		DirectCacheLine* L2DirectLines;
		FullCacheLine* L1FullLines;
		FullCacheLine* L2FullLines;
```

**Comment by T-King** [comment]
Go for it. I need to take a small break from it anyways. I'm going cross-eyed.

**Comment by krustchinsky** [comment]
I'll try to get the L2 stuff working tonight, tomorrow we can tackle the fully associative stuff. Shouldn't be all that hard. Good work
