### ISSUE TITLE
Associativity

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#23]
Jake, you mentioned adding some stuff for L2 soon. Can you give me an updated timeline? I want to keep working on it, but I don't want to step on your feet or accidentally implement something you're currently working on.

**Comment by krustchinsky** [comment]
Go ahead and work on anything you want to, I'm still toying around with things. I'll push anything I do to a different branch. We can finalize things on sunday

**Comment by T-King** [comment]
I still think I'm having trouble understanding how full associative works. Does each word have a tag? Or is it just 1 tag per line? The way I learned it in 2610 seems different from how Mashiro explained it.

**Comment by T-King** [comment]
Based on some online tutorials, it seems like each line would consist of 8 32-bit words (since we are using a 32-byte cache line). Each of those words per line would have 27 tag bits and 5 offset bits (and a valid bit I think). So we don't need block address or it's size. Does that sound correct?
