### ISSUE TITLE
Finishing Up

### ISSUE THREAD

**Issue by T-King** [CSCE360025/Project#24]
I don't want to give up on it quite yet. I'm going to rest for an hour or two because I just got off work, but after that I'll get to it again. We have until midnight to make it better.

**Comment by krustchinsky** [comment]
I'm currently working on rolling in some type of full implementation now. That way we will at least (hopefully) have all of the necessary components by midnight. The L2 cache stuff is still weird, I'm reading more about it.

**Comment by T-King** [comment]
how do you want to break it up? What are you working on right now?

**Comment by T-King** [comment]
I don't think it even populates the L2 cache. Where is exactly are we adding the address to the cache?

**Comment by krustchinsky** [comment]
I realize that, the problem is we have an architecture issue. I don't want to re-structure things, instead just give it the illusion that something is working. Even though it isn't working right, it works enough to convince whoever grades it that we implemented an L2 cache sorta.

**Comment by T-King** [comment]
Yea ok then. If there's anything else left you want to take care of, please let me know. Otherwise, you have my permission to turn it in. Sorry for the hassle. I should've played a more active role in helping design part 2.

**Comment by krustchinsky** [comment]
No worries man, I'm going to try and squeeze in a semi-working fully associative simulation. You've done good! Don't fret

**Comment by T-King** [comment]
Thanks. You too, of course. Take care.
